# This is a basic workflow to generate build
name: "pre-release"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for every branch
on:
  push:
    branches:
      - 'master'

  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'

  workflow_dispatch:
    inputs:
      comment:
        description: 'Add comment for manual workflow execution.'
        required: false
        default: 'Manual execution of Github workflow.'

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Generate App Build and Performing App Inspect Checks"
        run: |
          echo "Cyences App for Splunk"

      - uses: VatsalJagani/splunk-app-action@v1
        with:
          app_dir: "cyences_app_for_splunk"
          app_build_name: "cyences_app_for_splunk"
          splunkbase_username: ${{ secrets.SPLUNKBASE_USERNAME }}
          splunkbase_password: ${{ secrets.SPLUNKBASE_PASSWORD }}


      - name: "Generate Add-on Build and Performing App Inspect Checks"
        run: |
          echo "Cyences Add-on for Splunk"

      - uses: VatsalJagani/splunk-app-action@v1
        env:
          SPLUNK_APP_ACTION_1: "find TA-cyences -type f -name *.sh -exec chmod +x '{}' \;"
        with:
          app_dir: "TA-cyences"
          app_build_name: "TA-cyences"
          splunkbase_username: ${{ secrets.SPLUNKBASE_USERNAME }}
          splunkbase_password: ${{ secrets.SPLUNKBASE_PASSWORD }}
