# This is a basic workflow to generate build
name: "pre-release"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for every branch
on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
  workflow_dispatch:
    inputs:
      comment:
        description: 'Add comment for manual workflow execution.'
        required: false
        default: 'Manual execution of Github workflow.'

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    
    steps:
      # ...
      - name: "Generate App and Add-on Build"
        run: |
          echo "Started generating builds."
      
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}
          path: repodir
            
      - name: "Generate App Build"
        run: |
          cd repodir
          find cyences_app_for_splunk -type f -exec chmod 644 '{}' \;
          find cyences_app_for_splunk -type d -exec chmod 755 '{}' \;
          tar -czf cyences_app_for_splunk.tgz cyences_app_for_splunk
          cd ..
          
      - uses: actions/upload-artifact@v2
        with:
          name: "build"
          path: |
            repodir/cyences_app_for_splunk.tgz
      
      - name: "Generate Add-on Build"
        run: |
          cd repodir
          find TA-cyences -type f -exec chmod 644 '{}' \;
          find TA-cyences -type d -exec chmod 755 '{}' \;
          find TA-cyences -type f -name *.sh -exec chmod +x '{}' \;
          tar -czf TA-cyences.tgz TA-cyences
          cd ..
          
      - uses: actions/upload-artifact@v2
        with:
          name: "build"
          path: |
            repodir/TA-cyences.tgz
      
      - name: "Python Installation"
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64'

# Ref - https://dev.splunk.com/enterprise/docs/developapps/testvalidate/appinspect/splunkappinspectclitool/installappinspect/installappinspectonlinux
      - name: "Install App-Inspect"
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt-dev lib32z1-dev python-lxml
          sudo apt-get install libmagic-dev
          pip install https://download.splunk.com/misc/appinspect/splunk-appinspect-latest.tar.gz
 
      - name: "Running App-Inspect"
        run: |
          mkdir test_results || true
          splunk-appinspect inspect --mode test --data-format junitxml --output-file test_results/app-appinspect-mode-test.xml repodir/cyences_app_for_splunk.tgz
          splunk-appinspect inspect --mode test --data-format junitxml --output-file test_results/ta-appinspect-mode-test.xml repodir/TA-cyences.tgz
      
      - name: "Running Cloud-Inspect"
        run: |
          splunk-appinspect inspect --mode precert --included-tags cloud --data-format junitxml --output-file test_results/app-appinspect-mode-cloud.xml repodir/cyences_app_for_splunk.tgz
          splunk-appinspect inspect --mode precert --included-tags cloud --data-format junitxml --output-file test_results/ta-appinspect-mode-cloud.xml repodir/TA-cyences.tgz
      
      - uses: actions/upload-artifact@v2
        with:
          name: "app_inspect_reports"
          path: |
            test_results


      - name: "Inspect and Cloud Vetting Check"
        run: |
          if grep failures=\"[1-9] test_results/app-appinspect-mode-test.xml; then exit 1; else exit 0; fi
          if grep failures=\"[1-9] test_results/app-appinspect-mode-cloud.xml; then exit 1; else exit 0; fi
          if grep failures=\"[1-9] test_results/ta-appinspect-mode-test.xml; then exit 1; else exit 0; fi
          if grep failures=\"[1-9] test_results/ta-appinspect-mode-cloud.xml; then exit 1; else exit 0; fi
